version: '3.1'
services:
  quarkus-performance-db:
    image: mariadb
  spring-perfofrmance-db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=spring
      - MARIADB_PASSWORD=spring
      - MARIADB_DATABASE=spring
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  quarkus-native:
    image: quarkus-performance-native
    ports:
      - "8080:8080"
    environment:
     - DATASOURCE_USER=quarkus
  quarkus-jvm:
    image: quarkus-performance-jvm
    ports:
      - "8081:8080"
  
  spring-native:
    image: spring-performance-native
    ports:
    - "8082:8080"
    environment:
      - DATASOURCE_URL=jdbc:mariadb://localhost:3326/spring
  spring-jvm:
    image: spring-performance-jvm
